package main

import (
	"log"
	"os"

	_ "github.com/besser/goinaction/chapter2/matchers"
	"github.com/besser/goinaction/chapter2/search"
)

func init() {
	// Change the device for logging to stdout
	log.SetOutput(os.Stdout)

	// Define which text to prefix to each log entry generated by the Logger and with this flags produce:
	// 2009/01/23 01:23:23 /a/b/c/d.go:23: message
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}

func main() {
	term := os.Args[1]

	// Perform the search for the specified term
	search.Run(term)
}
